name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Verificar se o package.json existe
        run: ls -R  

      - name: Instalar dependências
        run: npm install

      - name: Rodar Testes
        run: npm test
